### PR TITLE
aaa ...

### PR DESCRIPTION
**Pull request by morlandi**
second try ...

### CODE REVIEW

**Comment by andreagrandi** [comment]
The code looks correct, but I can't make it show "aa" or "aaa", it always shows "a"

**Comment by morlandi** [comment]
there is always a trailing space added to the string to be displayed ... so you should start seeing "a ", then "aa " .... and so on. The more you shake, the longer is the "aaaa" stream

**Comment by andreagrandi** [comment]
@morlandi I see, but it doesn't behave as expected: I always see "a", never "aa" nor "aaa" etc...

**Comment by morlandi** [comment]
I do believe you missed my point ... at the beginning, you should see a blinking "a" .. then the more you shake, the more blinking slows down.
Never mind, thank you very much for the nice talk !

**Pull request closed without merging**
